### ISSUE TITLE
1.1.x-1.2.x multiversion support

### ISSUE THREAD

**Issue by Encritary** [PrismarineMC/Prismarine#37]
## Introduction
After Minecraft 1.2 Better Together release the new problem happened. Community of MC:PE/MC:BE was split in two parts: 1.1 players and 1.2 players. This problem is very noticeable in CIS countries, because here a lot of kids didn't buy license of Minecraft in GP or AS and they do not want to do something to make Xbox Live work on cracked 1.2.x version. So they are staying on 1.2. I'm sure there is same problem in other countries.
## Description
Multiversion is the best variant to solve this problem, but unfortunetaly there is only Steadfast supporting both 1.1.x and 1.2.x versions. But Steadfast isn't user friendly, it has a lot of useless code and there is a lot of "duct tapes", that can be rewritten into more logic code. Also Steadfast is based on PMMP 1.4, that means it has API lower than 1.13.0, and this is another problem for non-professional servers. I've started work on multiversion and I will upload what I did into development branch.

I need help with this project, I'm sure it will be awesome.
## TODO List
- [x] Convert PIDs and ContainerSetSlot/ContainerSetContent into InventorySlot/Content/PlayerHotbar packets
- [x] Make login sequence work
- [x] Multiprotocol chunk network serializing
- [ ] Fix crash of game after `Building terrain...`
- [ ] Up protocol from 160 to 200 after 1.2.10 release
- [ ] Enums of TextPacket and LevelSoundEventPacket
- [ ] Complete multiprotocol encoding of packets
- [ ] Convert transactions
- [ ] Crafting grid
- [ ] Multiprotocol sign spawn compound
- [ ] Block subclient login
- [ ] Allow to enable Xbox Live authentication checking only for 1.2+ clients
- [ ] More things...

**Comment by XoticRealmsOwnerandDev** [comment]
does it support 1.2 yet?????

**Comment by Encritary** [comment]
No
